services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FHIR_BASE_URL=https://r4.smarthealthit.org
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/fhir
      - FHIR_PAGE_SIZE=100
      # - FHIR_LAST_UPDATED_GTE=2025-01-01T00:00:00Z
    depends_on:
      - db
    volumes:
      - ./exports:/app/exports
      - ./scripts:/app/scripts:ro
  scheduler:
    image: alpine:3.20
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
      - ALERT_WEBHOOK_URL=${ALERT_WEBHOOK_URL}
    volumes:
      - ./scripts/cronjobs:/etc/crontabs/root:ro
      - ./scripts:/app/scripts:ro
    command: sh -c "apk add --no-cache curl && crond -f -l 2"

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fhir
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
