services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FHIR_BASE_URL=https://hapi.fhir.org/baseR4
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/fhir
      - FHIR_PAGE_SIZE=100
      # - FHIR_LAST_UPDATED_GTE=2025-01-01T00:00:00Z
    depends_on:
      - db
    volumes:
      - ./exports:/app/exports

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fhir
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
